export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const category = searchParams.get("category")

  const allProducts = [
    {
      id: 1,
      name: "Royal Silk Saree",
      category: "silk-sarees",
      price: 4999,
      originalPrice: 6999,
      rating: 4.8,
      reviews: 234,
      image: "/luxury-royal-silk-saree-with-gold-borders.jpg",
      description: "Exquisite royal silk saree with intricate golden borders",
      colors: ["Gold", "Maroon", "Navy"],
      fabric: "Pure Silk",
      featured: true,
    },
    {
      id: 2,
      name: "Bridal Elegance",
      category: "bridal-sarees",
      price: 8999,
      originalPrice: 12999,
      rating: 4.9,
      reviews: 189,
      image: "/bridal-saree-with-intricate-embroidery-and-zari-wo.jpg",
      description: "Stunning bridal saree with hand-embroidered details",
      colors: ["Red", "Maroon"],
      fabric: "Silk with Zari",
      featured: true,
    },
    {
      id: 3,
      name: "Cotton Comfort",
      category: "cotton-sarees",
      price: 1999,
      originalPrice: 2499,
      rating: 4.6,
      reviews: 412,
      image: "/comfortable-cotton-saree-with-traditional-motifs.jpg",
      description: "Breathable cotton saree perfect for daily wear",
      colors: ["White", "Cream", "Blue"],
      fabric: "Pure Cotton",
      featured: true,
    },
    {
      id: 4,
      name: "Modern Fusion",
      category: "designer-sarees",
      price: 5999,
      originalPrice: 7999,
      rating: 4.7,
      reviews: 156,
      image: "/modern-designer-saree-contemporary-patterns.jpg",
      description: "Contemporary design with traditional elements",
      colors: ["Black", "Gray", "Wine"],
      fabric: "Blend",
      featured: false,
    },
    {
      id: 5,
      name: "Silk Heritage",
      category: "silk-sarees",
      price: 3999,
      originalPrice: 5499,
      rating: 4.7,
      reviews: 267,
      image: "/heritage-silk-saree-with-traditional-patterns.jpg",
      description: "Traditional patterns on premium silk",
      colors: ["Green", "Purple", "Gold"],
      fabric: "Pure Silk",
      featured: false,
    },
    {
      id: 6,
      name: "Festival Dreams",
      category: "cotton-sarees",
      price: 2499,
      originalPrice: 3299,
      rating: 4.5,
      reviews: 328,
      image: "/festival-cotton-saree-colorful-vibrant.jpg",
      description: "Colorful saree for festive celebrations",
      colors: ["Orange", "Red", "Pink"],
      fabric: "Pure Cotton",
      featured: false,
    },
    {
      id: 7,
      name: "Silk Dreams",
      category: "silk-sarees",
      price: 4499,
      originalPrice: 6299,
      rating: 4.8,
      reviews: 201,
      image: "/elegant-silk-saree-pastels-soft-colors.jpg",
      description: "Soft pastels on luxurious silk",
      colors: ["Peach", "Cream", "Lavender"],
      fabric: "Pure Silk",
      featured: false,
    },
    {
      id: 8,
      name: "Designer Elegance",
      category: "designer-sarees",
      price: 6999,
      originalPrice: 9499,
      rating: 4.9,
      reviews: 145,
      image: "/high-fashion-designer-saree-luxury-collection.jpg",
      description: "Haute couture designer saree",
      colors: ["Black", "Gold", "Silver"],
      fabric: "Premium Blend",
      featured: true,
    },
  ]

  const filteredProducts = category ? allProducts.filter((p) => p.category === category) : allProducts

  return Response.json(filteredProducts)
}
